### ISSUE TITLE
Equivalence Checking is reporting zero veritesting regions for SPFCases

### ISSUE THREAD

**Issue by sohah** [sohah/VeritestingTransformations#19]
I know we probably expected some work for the equivalence checking to work with SPFCases. I am putting this up just as a reference for the work to be done on the equivalence checking in this direction. besides issue#18, equivalence checking is reporting zero veritesting regions when SPFCases is used, despite the fact when the same example runs without the equivalence checking the correct number of veritesting regions are reported. The example I used is [here](https://github.com/sohah/VeritestingTransformations/blob/master/src/examples/EqSPFCasesTest1.java) and the .jpf file is [here](https://github.com/sohah/VeritestingTransformations/blob/master/src/examples/EqSPFCasesTest1.jpf).

**Comment by vaibhavbsharma** [comment]
I'm not sure I am understanding this bug report correctly. I've now fixed [Issue 18](https://github.com/sohah/VeritestingTransformations/issues/18). With that issue fixed, here's the report that gets generated for EqSPFCasesTest1. This report shows that Java Ranger now instantiates 6 regions during equivalence-checking for EqSPFCasesTest1. Would it be accurate to say that this issue is now fixed ? If not, can you please provide me with another example where this issue continues to persist ?

====================================================== VeritestingListener report:

/************************ Printing Regions Statistics *****************
veriHitNumber: number of times a region was successfully veritested
spfHitNumber: number of times we were not able to veritest a region and we left it to SPF (this is counting failures due to statements in the region we couldn't summaries.)
concreteHit: number of times a region was not veritested because of the condition

*** Region Key = Outputs.equals(Ljava/lang/Object;)Z#24
veriHitNumber | spfHitNumber | concreteHit
0      | 0         | 4
-------------------------------------------
Fail Reasons

*** Region Key = EqSPFCasesTest1.createObjectTC8(ZZ)LOutputs;#27
veriHitNumber | spfHitNumber | concreteHit
4      | 0         | 0
-------------------------------------------
Fail Reasons

*** Region Key = EqSPFCasesTest1.createObjectTC8(ZZ)LOutputs;#3
veriHitNumber | spfHitNumber | concreteHit
2      | 0         | 0
-------------------------------------------
Fail Reasons

*** Region Key = Outputs.equals(Ljava/lang/Object;)Z#60
veriHitNumber | spfHitNumber | concreteHit
0      | 4         | 0
-------------------------------------------
Fail Reasons
gov.nasa.jpf.symbc.veritesting.VeritestingUtil.FailEntry@750a04ec - FailInstruction = fillFieldInputHole: class loader failed to resolve class name Systemgov.nasa.jpf.symbc.veritesting.VeritestingUtil.FailEntry@49e2b3c5 - FailInstruction = fillFieldInputHole: class loader failed to resolve class name Systemgov.nasa.jpf.symbc.veritesting.VeritestingUtil.FailEntry@56846330 - FailInstruction = fillFieldInputHole: class loader failed to resolve class name Systemgov.nasa.jpf.symbc.veritesting.VeritestingUtil.FailEntry@49f3ff41 - FailInstruction = fillFieldInputHole: class loader failed to resolve class name System

/************************ Printing Time Decomposition Statistics *****************
static analysis time = 703 msec
Veritesting Dyn Time = 648 msec

/************************ Printing Solver Statistics *****************
Total Solver Queries Count = 38
Total Solver Time = 94 msec
Total Solver Parse Time = 45 msec
Total Solver Clean up Time = 2 msec

/************************ Printing Accumulative Statistics *****************
Number of Distinct Veritested Regions = 2
Number of Distinct Un-Veritested Symbolic Regions = 1
Number of Distinct Un-Veritested Concrete Regions = 1
Number of Distinct Failed Regions for Field Reference = 1
Number of Distinct Failed Regions for SPFCases = 0
Number of Distinct Failed Regions for Other Reasons = 0
Total number of Distinct regions = 4
Number of Veritested Regions Instances = 6
Expected Number of Veritested Regions Instances = 6

====================================================== results
no errors detected

====================================================== statistics
elapsed time:       00:00:01
states:             new=32,visited=0,backtracked=32,end=4
search:             maxDepth=6,constraints=0
choice generators:  thread=1 (signal=0,lock=1,sharedRef=0,threadApi=0,reschedule=0), data=12
heap:               new=410,released=78,maxLive=365,gcCycles=12
instructions:       3971
max memory:         240MB
loaded code:        classes=65,methods=1302

====================================================== search finished: 10/9/18 4:43 PM

Process finished with exit code 0

**Comment by sohah** [comment]
That fixes it. I am closing the issue.
