### ISSUE TITLE
Region boundary should not be applied if no boundary was found

### ISSUE THREAD

**Issue by vaibhavbsharma** [sohah/VeritestingTransformations#5]
Here's an example:

```Java
public class VeritestingPerf {
    public int count = 0;
    public int fieldWriteTestBranch2(int x) {
        if (x != 0) count = 1;
        else count = 2;
        return count;
    }
}
```
The region inside `fieldWriteTestBranch2` has two writes to fields. This causes no new wala variables to be defined inside the region in Wala IR. When computing the region boundary in `StaticRegion.computeRegionBoundary`, we find the `firstDef` and the `lastDef` to both be 0. These `firstDef` and `lastDef` variables still have their default values which should not be used to filter the `SlotParamTable`. If we fail to find a region boundary, we shouldn't try to use the default values for the region boundary. 

This bug manifests itself by causing all the entries to be filtered out in `SlotParamTable` because `firstUse` is set to 1 in `SlotParamTable.filterTableForBoundary` and `lastDef` is set to 0.

**Comment by sohah** [comment]
The problem here was that the region boundary was defined to include all the vars between the first use and the last def inside the region. However this definition is not entirely correct in case of field references because a region can have no def inside it. To handle this case change has been made to define the region end by the last use var instead.
